### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ghost** [TomSimpsonNZ/Rust-Light-Vulkan-Engine#2]
i use your code from this commit c907711f7a703745efedc4e8640956a3a98d9312 and added fps counter and I was getting about 2600 fps but i was getting about 5400 fps with gfx-hal. i am currently working on a game engine with wgpu-hal as backend and with some multithreading i was able to get more than 7500 fps my application was drawing a simple red triangle with multisampling and depth testing enable
backend was set to vulkan when testing

**Comment by TomSimpsonNZ** [comment]
Yeah that performance does seem pretty poor doesn’t it… 

I can maybe think of a few reasons why this might be the case (but idk if this is actually right because I don’t know you gfx/wgpu-Hal code), for such a simple example such as this, every function call would matter. By braking everything up into their own modules there will probably be a bunch of overhead that is really noticeable when we are only drawing one triangle. I would like to see how this code compares to gfx-Hal for more complicated examples though!

But yeah, the purpose of this repository was to translate/port a specific C++ vulkan tutorial as closely as possible, so it could be that this design/layout sacrifices raw performance for better usability. At the end of the day, I am still new to rust and vulkan/ash so have no doubt made a bunch of silly mistakes, but that’s the fun of learning!
